//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecSignerSoapExample.SecSignerNs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://seccommerce.de/ws/SecPKI/", ConfigurationName="SecSignerNs.SecSignerSoapPortType")]
    public interface SecSignerSoapPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (SignResult) of message signResponse does not match the default value (sign)
        [System.ServiceModel.OperationContractAttribute(Action="sign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SecSignerSoapExample.SecSignerNs.signResponse sign(SecSignerSoapExample.SecSignerNs.signRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sign", ReplyAction="*")]
        System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.signResponse> signAsync(SecSignerSoapExample.SecSignerNs.signRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (VerifyResult) of message verifyResponse does not match the default value (verify)
        [System.ServiceModel.OperationContractAttribute(Action="verify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SecSignerSoapExample.SecSignerNs.verifyResponse verify(SecSignerSoapExample.SecSignerNs.verifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="verify", ReplyAction="*")]
        System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.verifyResponse> verifyAsync(SecSignerSoapExample.SecSignerNs.verifyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class SignReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureRecord[] signatureRecordField;
        
        private byte[][] cipherCertField;
        
        private byte[] signatureKeyField;
        
        private byte[] signatureCertField;
        
        private byte[][] attributeCertField;
        
        private bool modalField;
        
        private bool modalSpecified;
        
        private bool alwaysOnTopField;
        
        private bool alwaysOnTopSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SignatureRecordElem")]
        public SignatureRecord[] SignatureRecord {
            get {
                return this.signatureRecordField;
            }
            set {
                this.signatureRecordField = value;
                this.RaisePropertyChanged("SignatureRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CipherCertElem", DataType="base64Binary")]
        public byte[][] CipherCert {
            get {
                return this.cipherCertField;
            }
            set {
                this.cipherCertField = value;
                this.RaisePropertyChanged("CipherCert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureKey {
            get {
                return this.signatureKeyField;
            }
            set {
                this.signatureKeyField = value;
                this.RaisePropertyChanged("SignatureKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureCert {
            get {
                return this.signatureCertField;
            }
            set {
                this.signatureCertField = value;
                this.RaisePropertyChanged("SignatureCert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeCertElem", DataType="base64Binary")]
        public byte[][] AttributeCert {
            get {
                return this.attributeCertField;
            }
            set {
                this.attributeCertField = value;
                this.RaisePropertyChanged("AttributeCert");
            }
        }
        
        /// <remarks/>
        public bool Modal {
            get {
                return this.modalField;
            }
            set {
                this.modalField = value;
                this.RaisePropertyChanged("Modal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModalSpecified {
            get {
                return this.modalSpecified;
            }
            set {
                this.modalSpecified = value;
                this.RaisePropertyChanged("ModalSpecified");
            }
        }
        
        /// <remarks/>
        public bool AlwaysOnTop {
            get {
                return this.alwaysOnTopField;
            }
            set {
                this.alwaysOnTopField = value;
                this.RaisePropertyChanged("AlwaysOnTop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlwaysOnTopSpecified {
            get {
                return this.alwaysOnTopSpecified;
            }
            set {
                this.alwaysOnTopSpecified = value;
                this.RaisePropertyChanged("AlwaysOnTopSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class SignatureRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] signatureField;
        
        private byte[] timestampField;
        
        private byte[] certificateField;
        
        private string hashAlgorithmField;
        
        private string[] verificationReportsField;
        
        private byte[] signatureCipheredField;
        
        private string verificationReportXmlField;
        
        private string documentFileNameField;
        
        private string verificationReportField;
        
        private string signatureFileNameField;
        
        private string xmlDSigNameSpaceNameField;
        
        private XmlDSigTransformFilter[] xmlDSigTransformFilterField;
        
        private int signatureFormatTypeField;
        
        private bool signatureFormatTypeFieldSpecified;
        
        private string xmlDSigNodePathField;
        
        private byte[][] evidenceRecordsField;
        
        private string signersProfessionInfoField;
        
        private string overallVerificationReportField;
        
        private string xmlDSigReferenceUriField;
        
        private bool includeSignatureIntoPDFField;
        
        private bool includeSignatureIntoPDFFieldSpecified;
        
        private bool includeToBeSignedDataField;
        
        private bool includeToBeSignedDataFieldSpecified;
        
        private bool includeDocumentField;
        
        private bool includeDocumentFieldSpecified;
        
        private string[] evidenceRecordFileNamesField;
        
        private bool includeSignersCertificateField;
        
        private bool includeSignersCertificateFieldSpecified;
        
        private string signatureUrlField;
        
        private PDFAnnotation pDFAnnotationField;
        
        private byte[] oldSignatureField;
        
        private string documentUrlField;
        
        private byte[] documentField;
        
        private string dataUrlField;
        
        private int documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private byte[] cipheredDataField;
        
        private string descriptionField;
        
        private string signatureIDField;
        
        private bool pssPaddingField;
        
        private bool pssPaddingFieldSpecified;
        
        private string charsetField;
        
        private int numberOfSignersField;
        
        private bool numberOfSignersFieldSpecified;
        
        private string documentFileNameExtensionField;
        
        private byte[] signatureDecryptedField;
        
        private byte[] dataToSignCipheredField;
        
        private byte[] ocspResponseFirstSignerField;
        
        private byte[] documentCipheredField;
        
        private bool inputStreamNullField;
        
        private bool inputStreamNullFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
                this.RaisePropertyChanged("Certificate");
            }
        }
        
        /// <remarks/>
        public string HashAlgorithm {
            get {
                return this.hashAlgorithmField;
            }
            set {
                this.hashAlgorithmField = value;
                this.RaisePropertyChanged("HashAlgorithm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("VerificationReportsElem")]
        public string[] VerificationReports {
            get {
                return this.verificationReportsField;
            }
            set {
                this.verificationReportsField = value;
                this.RaisePropertyChanged("VerificationReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureCiphered {
            get {
                return this.signatureCipheredField;
            }
            set {
                this.signatureCipheredField = value;
                this.RaisePropertyChanged("SignatureCiphered");
            }
        }
        
        /// <remarks/>
        public string VerificationReportXml {
            get {
                return this.verificationReportXmlField;
            }
            set {
                this.verificationReportXmlField = value;
                this.RaisePropertyChanged("VerificationReportXml");
            }
        }
        
        /// <remarks/>
        public string DocumentFileName {
            get {
                return this.documentFileNameField;
            }
            set {
                this.documentFileNameField = value;
                this.RaisePropertyChanged("DocumentFileName");
            }
        }
        
        /// <remarks/>
        public string VerificationReport {
            get {
                return this.verificationReportField;
            }
            set {
                this.verificationReportField = value;
                this.RaisePropertyChanged("VerificationReport");
            }
        }
        
        /// <remarks/>
        public string SignatureFileName {
            get {
                return this.signatureFileNameField;
            }
            set {
                this.signatureFileNameField = value;
                this.RaisePropertyChanged("SignatureFileName");
            }
        }
        
        /// <remarks/>
        public string XmlDSigNameSpaceName {
            get {
                return this.xmlDSigNameSpaceNameField;
            }
            set {
                this.xmlDSigNameSpaceNameField = value;
                this.RaisePropertyChanged("XmlDSigNameSpaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("XmlDSigTransformFilterElem")]
        public XmlDSigTransformFilter[] XmlDSigTransformFilter {
            get {
                return this.xmlDSigTransformFilterField;
            }
            set {
                this.xmlDSigTransformFilterField = value;
                this.RaisePropertyChanged("XmlDSigTransformFilter");
            }
        }
        
        /// <remarks/>
        public int SignatureFormatType {
            get {
                return this.signatureFormatTypeField;
            }
            set {
                this.signatureFormatTypeField = value;
                this.RaisePropertyChanged("SignatureFormatType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignatureFormatTypeSpecified {
            get {
                return this.signatureFormatTypeFieldSpecified;
            }
            set {
                this.signatureFormatTypeFieldSpecified = value;
                this.RaisePropertyChanged("SignatureFormatTypeSpecified");
            }
        }
        
        /// <remarks/>
        public string XmlDSigNodePath {
            get {
                return this.xmlDSigNodePathField;
            }
            set {
                this.xmlDSigNodePathField = value;
                this.RaisePropertyChanged("XmlDSigNodePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EvidenceRecordsElem", DataType="base64Binary")]
        public byte[][] EvidenceRecords {
            get {
                return this.evidenceRecordsField;
            }
            set {
                this.evidenceRecordsField = value;
                this.RaisePropertyChanged("EvidenceRecords");
            }
        }
        
        /// <remarks/>
        public string SignersProfessionInfo {
            get {
                return this.signersProfessionInfoField;
            }
            set {
                this.signersProfessionInfoField = value;
                this.RaisePropertyChanged("SignersProfessionInfo");
            }
        }
        
        /// <remarks/>
        public string OverallVerificationReport {
            get {
                return this.overallVerificationReportField;
            }
            set {
                this.overallVerificationReportField = value;
                this.RaisePropertyChanged("OverallVerificationReport");
            }
        }
        
        /// <remarks/>
        public string XmlDSigReferenceUri {
            get {
                return this.xmlDSigReferenceUriField;
            }
            set {
                this.xmlDSigReferenceUriField = value;
                this.RaisePropertyChanged("XmlDSigReferenceUri");
            }
        }
        
        /// <remarks/>
        public bool IncludeSignatureIntoPDF {
            get {
                return this.includeSignatureIntoPDFField;
            }
            set {
                this.includeSignatureIntoPDFField = value;
                this.RaisePropertyChanged("IncludeSignatureIntoPDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeSignatureIntoPDFSpecified {
            get {
                return this.includeSignatureIntoPDFFieldSpecified;
            }
            set {
                this.includeSignatureIntoPDFFieldSpecified = value;
                this.RaisePropertyChanged("IncludeSignatureIntoPDFSpecified");
            }
        }
        
        /// <remarks/>
        public bool IncludeToBeSignedData {
            get {
                return this.includeToBeSignedDataField;
            }
            set {
                this.includeToBeSignedDataField = value;
                this.RaisePropertyChanged("IncludeToBeSignedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeToBeSignedDataSpecified {
            get {
                return this.includeToBeSignedDataFieldSpecified;
            }
            set {
                this.includeToBeSignedDataFieldSpecified = value;
                this.RaisePropertyChanged("IncludeToBeSignedDataSpecified");
            }
        }
        
        /// <remarks/>
        public bool IncludeDocument {
            get {
                return this.includeDocumentField;
            }
            set {
                this.includeDocumentField = value;
                this.RaisePropertyChanged("IncludeDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeDocumentSpecified {
            get {
                return this.includeDocumentFieldSpecified;
            }
            set {
                this.includeDocumentFieldSpecified = value;
                this.RaisePropertyChanged("IncludeDocumentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EvidenceRecordFileNamesElem")]
        public string[] EvidenceRecordFileNames {
            get {
                return this.evidenceRecordFileNamesField;
            }
            set {
                this.evidenceRecordFileNamesField = value;
                this.RaisePropertyChanged("EvidenceRecordFileNames");
            }
        }
        
        /// <remarks/>
        public bool IncludeSignersCertificate {
            get {
                return this.includeSignersCertificateField;
            }
            set {
                this.includeSignersCertificateField = value;
                this.RaisePropertyChanged("IncludeSignersCertificate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeSignersCertificateSpecified {
            get {
                return this.includeSignersCertificateFieldSpecified;
            }
            set {
                this.includeSignersCertificateFieldSpecified = value;
                this.RaisePropertyChanged("IncludeSignersCertificateSpecified");
            }
        }
        
        /// <remarks/>
        public string SignatureUrl {
            get {
                return this.signatureUrlField;
            }
            set {
                this.signatureUrlField = value;
                this.RaisePropertyChanged("SignatureUrl");
            }
        }
        
        /// <remarks/>
        public PDFAnnotation PDFAnnotation {
            get {
                return this.pDFAnnotationField;
            }
            set {
                this.pDFAnnotationField = value;
                this.RaisePropertyChanged("PDFAnnotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] OldSignature {
            get {
                return this.oldSignatureField;
            }
            set {
                this.oldSignatureField = value;
                this.RaisePropertyChanged("OldSignature");
            }
        }
        
        /// <remarks/>
        public string DocumentUrl {
            get {
                return this.documentUrlField;
            }
            set {
                this.documentUrlField = value;
                this.RaisePropertyChanged("DocumentUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        /// <remarks/>
        public string DataUrl {
            get {
                return this.dataUrlField;
            }
            set {
                this.dataUrlField = value;
                this.RaisePropertyChanged("DataUrl");
            }
        }
        
        /// <remarks/>
        public int DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
                this.RaisePropertyChanged("DocumentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CipheredData {
            get {
                return this.cipheredDataField;
            }
            set {
                this.cipheredDataField = value;
                this.RaisePropertyChanged("CipheredData");
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        public string SignatureID {
            get {
                return this.signatureIDField;
            }
            set {
                this.signatureIDField = value;
                this.RaisePropertyChanged("SignatureID");
            }
        }
        
        /// <remarks/>
        public bool PssPadding {
            get {
                return this.pssPaddingField;
            }
            set {
                this.pssPaddingField = value;
                this.RaisePropertyChanged("PssPadding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PssPaddingSpecified {
            get {
                return this.pssPaddingFieldSpecified;
            }
            set {
                this.pssPaddingFieldSpecified = value;
                this.RaisePropertyChanged("PssPaddingSpecified");
            }
        }
        
        /// <remarks/>
        public string Charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
                this.RaisePropertyChanged("Charset");
            }
        }
        
        /// <remarks/>
        public int NumberOfSigners {
            get {
                return this.numberOfSignersField;
            }
            set {
                this.numberOfSignersField = value;
                this.RaisePropertyChanged("NumberOfSigners");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfSignersSpecified {
            get {
                return this.numberOfSignersFieldSpecified;
            }
            set {
                this.numberOfSignersFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfSignersSpecified");
            }
        }
        
        /// <remarks/>
        public string DocumentFileNameExtension {
            get {
                return this.documentFileNameExtensionField;
            }
            set {
                this.documentFileNameExtensionField = value;
                this.RaisePropertyChanged("DocumentFileNameExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureDecrypted {
            get {
                return this.signatureDecryptedField;
            }
            set {
                this.signatureDecryptedField = value;
                this.RaisePropertyChanged("SignatureDecrypted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DataToSignCiphered {
            get {
                return this.dataToSignCipheredField;
            }
            set {
                this.dataToSignCipheredField = value;
                this.RaisePropertyChanged("DataToSignCiphered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] OcspResponseFirstSigner {
            get {
                return this.ocspResponseFirstSignerField;
            }
            set {
                this.ocspResponseFirstSignerField = value;
                this.RaisePropertyChanged("OcspResponseFirstSigner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DocumentCiphered {
            get {
                return this.documentCipheredField;
            }
            set {
                this.documentCipheredField = value;
                this.RaisePropertyChanged("DocumentCiphered");
            }
        }
        
        /// <remarks/>
        public bool InputStreamNull {
            get {
                return this.inputStreamNullField;
            }
            set {
                this.inputStreamNullField = value;
                this.RaisePropertyChanged("InputStreamNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InputStreamNullSpecified {
            get {
                return this.inputStreamNullFieldSpecified;
            }
            set {
                this.inputStreamNullFieldSpecified = value;
                this.RaisePropertyChanged("InputStreamNullSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class XmlDSigTransformFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int transformMethodField;
        
        private bool transformMethodFieldSpecified;
        
        private string transformMethodStringField;
        
        private string xPathExpressionField;
        
        private NameSpacePrefixDefs[] nameSpacePrefixDefsField;
        
        /// <remarks/>
        public int TransformMethod {
            get {
                return this.transformMethodField;
            }
            set {
                this.transformMethodField = value;
                this.RaisePropertyChanged("TransformMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransformMethodSpecified {
            get {
                return this.transformMethodFieldSpecified;
            }
            set {
                this.transformMethodFieldSpecified = value;
                this.RaisePropertyChanged("TransformMethodSpecified");
            }
        }
        
        /// <remarks/>
        public string TransformMethodString {
            get {
                return this.transformMethodStringField;
            }
            set {
                this.transformMethodStringField = value;
                this.RaisePropertyChanged("TransformMethodString");
            }
        }
        
        /// <remarks/>
        public string XPathExpression {
            get {
                return this.xPathExpressionField;
            }
            set {
                this.xPathExpressionField = value;
                this.RaisePropertyChanged("XPathExpression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NameSpacePrefixDefsElem")]
        public NameSpacePrefixDefs[] NameSpacePrefixDefs {
            get {
                return this.nameSpacePrefixDefsField;
            }
            set {
                this.nameSpacePrefixDefsField = value;
                this.RaisePropertyChanged("NameSpacePrefixDefs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class NameSpacePrefixDefs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prefixField;
        
        private string uriField;
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
                this.RaisePropertyChanged("Prefix");
            }
        }
        
        /// <remarks/>
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("Uri");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class VerifyRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private bool resultCodeFieldSpecified;
        
        private SignatureRecord[] signatureRecordField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultCodeSpecified {
            get {
                return this.resultCodeFieldSpecified;
            }
            set {
                this.resultCodeFieldSpecified = value;
                this.RaisePropertyChanged("ResultCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SignatureRecordElem")]
        public SignatureRecord[] SignatureRecord {
            get {
                return this.signatureRecordField;
            }
            set {
                this.signatureRecordField = value;
                this.RaisePropertyChanged("SignatureRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class VerifyReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureRecord[] signatureRecordField;
        
        private byte[][] externSignersCertsDerField;
        
        private bool allowSigField;
        
        private bool allowSigFieldSpecified;
        
        private bool offerFileOpenDlgField;
        
        private bool offerFileOpenDlgFieldSpecified;
        
        private bool ocspMandatoryField;
        
        private bool ocspMandatoryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SignatureRecordElem")]
        public SignatureRecord[] SignatureRecord {
            get {
                return this.signatureRecordField;
            }
            set {
                this.signatureRecordField = value;
                this.RaisePropertyChanged("SignatureRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExternSignersCertsDerElem", DataType="base64Binary")]
        public byte[][] ExternSignersCertsDer {
            get {
                return this.externSignersCertsDerField;
            }
            set {
                this.externSignersCertsDerField = value;
                this.RaisePropertyChanged("ExternSignersCertsDer");
            }
        }
        
        /// <remarks/>
        public bool AllowSig {
            get {
                return this.allowSigField;
            }
            set {
                this.allowSigField = value;
                this.RaisePropertyChanged("AllowSig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowSigSpecified {
            get {
                return this.allowSigFieldSpecified;
            }
            set {
                this.allowSigFieldSpecified = value;
                this.RaisePropertyChanged("AllowSigSpecified");
            }
        }
        
        /// <remarks/>
        public bool OfferFileOpenDlg {
            get {
                return this.offerFileOpenDlgField;
            }
            set {
                this.offerFileOpenDlgField = value;
                this.RaisePropertyChanged("OfferFileOpenDlg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OfferFileOpenDlgSpecified {
            get {
                return this.offerFileOpenDlgFieldSpecified;
            }
            set {
                this.offerFileOpenDlgFieldSpecified = value;
                this.RaisePropertyChanged("OfferFileOpenDlgSpecified");
            }
        }
        
        /// <remarks/>
        public bool OcspMandatory {
            get {
                return this.ocspMandatoryField;
            }
            set {
                this.ocspMandatoryField = value;
                this.RaisePropertyChanged("OcspMandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OcspMandatorySpecified {
            get {
                return this.ocspMandatoryFieldSpecified;
            }
            set {
                this.ocspMandatoryFieldSpecified = value;
                this.RaisePropertyChanged("OcspMandatorySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class SignRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureRecord[] signatureRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SignatureRecordElem")]
        public SignatureRecord[] SignatureRecord {
            get {
                return this.signatureRecordField;
            }
            set {
                this.signatureRecordField = value;
                this.RaisePropertyChanged("SignatureRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seccommerce.de/ws/SecPKI/")]
    public partial class PDFAnnotation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] pdfSigImageField;
        
        private byte[] pdfLinkImageField;
        
        private string pdfSigReasonField;
        
        private int pdfSigPaddingField;
        
        private bool pdfSigPaddingFieldSpecified;
        
        private string pdfLinkUrlField;
        
        private string rootDirField;
        
        private int pdfSigHeightField;
        
        private bool pdfSigHeightFieldSpecified;
        
        private int pdfSigWidthField;
        
        private bool pdfSigWidthFieldSpecified;
        
        private bool pdfShowSignerIconField;
        
        private bool pdfShowSignerIconFieldSpecified;
        
        private bool pdfSigAnnotLabelsField;
        
        private bool pdfSigAnnotLabelsFieldSpecified;
        
        private byte[] pdfSigBackgroundImageField;
        
        private bool pdfDisplayAnnotationField;
        
        private bool pdfDisplayAnnotationFieldSpecified;
        
        private bool pdfSigShowDateField;
        
        private bool pdfSigShowDateFieldSpecified;
        
        private byte[] pdfSignatureSignedImageField;
        
        private bool pdfSigImageTextField;
        
        private bool pdfSigImageTextFieldSpecified;
        
        private string pdfSigLocationField;
        
        private string pdfSignatureTextAnnotField;
        
        private byte[] pdfSignatureSignerIconField;
        
        private string pdfSigPositionInFormFieldField;
        
        private int pdfSigPositionField;
        
        private bool pdfSigPositionFieldSpecified;
        
        private bool pdfTransparentBackgroundField;
        
        private bool pdfTransparentBackgroundFieldSpecified;
        
        private bool pdfScaleSigImageField;
        
        private bool pdfScaleSigImageFieldSpecified;
        
        private string pdfSigTextSizeAndPositionField;
        
        private bool invertPageRotationField;
        
        private bool invertPageRotationFieldSpecified;
        
        private bool pdfShowSignedImageField;
        
        private bool pdfShowSignedImageFieldSpecified;
        
        private bool pdfSigBackgroundImageTextOverlayField;
        
        private bool pdfSigBackgroundImageTextOverlayFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PdfSigImage {
            get {
                return this.pdfSigImageField;
            }
            set {
                this.pdfSigImageField = value;
                this.RaisePropertyChanged("PdfSigImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PdfLinkImage {
            get {
                return this.pdfLinkImageField;
            }
            set {
                this.pdfLinkImageField = value;
                this.RaisePropertyChanged("PdfLinkImage");
            }
        }
        
        /// <remarks/>
        public string PdfSigReason {
            get {
                return this.pdfSigReasonField;
            }
            set {
                this.pdfSigReasonField = value;
                this.RaisePropertyChanged("PdfSigReason");
            }
        }
        
        /// <remarks/>
        public int PdfSigPadding {
            get {
                return this.pdfSigPaddingField;
            }
            set {
                this.pdfSigPaddingField = value;
                this.RaisePropertyChanged("PdfSigPadding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigPaddingSpecified {
            get {
                return this.pdfSigPaddingFieldSpecified;
            }
            set {
                this.pdfSigPaddingFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigPaddingSpecified");
            }
        }
        
        /// <remarks/>
        public string PdfLinkUrl {
            get {
                return this.pdfLinkUrlField;
            }
            set {
                this.pdfLinkUrlField = value;
                this.RaisePropertyChanged("PdfLinkUrl");
            }
        }
        
        /// <remarks/>
        public string RootDir {
            get {
                return this.rootDirField;
            }
            set {
                this.rootDirField = value;
                this.RaisePropertyChanged("RootDir");
            }
        }
        
        /// <remarks/>
        public int PdfSigHeight {
            get {
                return this.pdfSigHeightField;
            }
            set {
                this.pdfSigHeightField = value;
                this.RaisePropertyChanged("PdfSigHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigHeightSpecified {
            get {
                return this.pdfSigHeightFieldSpecified;
            }
            set {
                this.pdfSigHeightFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigHeightSpecified");
            }
        }
        
        /// <remarks/>
        public int PdfSigWidth {
            get {
                return this.pdfSigWidthField;
            }
            set {
                this.pdfSigWidthField = value;
                this.RaisePropertyChanged("PdfSigWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigWidthSpecified {
            get {
                return this.pdfSigWidthFieldSpecified;
            }
            set {
                this.pdfSigWidthFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigWidthSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfShowSignerIcon {
            get {
                return this.pdfShowSignerIconField;
            }
            set {
                this.pdfShowSignerIconField = value;
                this.RaisePropertyChanged("PdfShowSignerIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfShowSignerIconSpecified {
            get {
                return this.pdfShowSignerIconFieldSpecified;
            }
            set {
                this.pdfShowSignerIconFieldSpecified = value;
                this.RaisePropertyChanged("PdfShowSignerIconSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfSigAnnotLabels {
            get {
                return this.pdfSigAnnotLabelsField;
            }
            set {
                this.pdfSigAnnotLabelsField = value;
                this.RaisePropertyChanged("PdfSigAnnotLabels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigAnnotLabelsSpecified {
            get {
                return this.pdfSigAnnotLabelsFieldSpecified;
            }
            set {
                this.pdfSigAnnotLabelsFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigAnnotLabelsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PdfSigBackgroundImage {
            get {
                return this.pdfSigBackgroundImageField;
            }
            set {
                this.pdfSigBackgroundImageField = value;
                this.RaisePropertyChanged("PdfSigBackgroundImage");
            }
        }
        
        /// <remarks/>
        public bool PdfDisplayAnnotation {
            get {
                return this.pdfDisplayAnnotationField;
            }
            set {
                this.pdfDisplayAnnotationField = value;
                this.RaisePropertyChanged("PdfDisplayAnnotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfDisplayAnnotationSpecified {
            get {
                return this.pdfDisplayAnnotationFieldSpecified;
            }
            set {
                this.pdfDisplayAnnotationFieldSpecified = value;
                this.RaisePropertyChanged("PdfDisplayAnnotationSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfSigShowDate {
            get {
                return this.pdfSigShowDateField;
            }
            set {
                this.pdfSigShowDateField = value;
                this.RaisePropertyChanged("PdfSigShowDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigShowDateSpecified {
            get {
                return this.pdfSigShowDateFieldSpecified;
            }
            set {
                this.pdfSigShowDateFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigShowDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PdfSignatureSignedImage {
            get {
                return this.pdfSignatureSignedImageField;
            }
            set {
                this.pdfSignatureSignedImageField = value;
                this.RaisePropertyChanged("PdfSignatureSignedImage");
            }
        }
        
        /// <remarks/>
        public bool PdfSigImageText {
            get {
                return this.pdfSigImageTextField;
            }
            set {
                this.pdfSigImageTextField = value;
                this.RaisePropertyChanged("PdfSigImageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigImageTextSpecified {
            get {
                return this.pdfSigImageTextFieldSpecified;
            }
            set {
                this.pdfSigImageTextFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigImageTextSpecified");
            }
        }
        
        /// <remarks/>
        public string PdfSigLocation {
            get {
                return this.pdfSigLocationField;
            }
            set {
                this.pdfSigLocationField = value;
                this.RaisePropertyChanged("PdfSigLocation");
            }
        }
        
        /// <remarks/>
        public string PdfSignatureTextAnnot {
            get {
                return this.pdfSignatureTextAnnotField;
            }
            set {
                this.pdfSignatureTextAnnotField = value;
                this.RaisePropertyChanged("PdfSignatureTextAnnot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PdfSignatureSignerIcon {
            get {
                return this.pdfSignatureSignerIconField;
            }
            set {
                this.pdfSignatureSignerIconField = value;
                this.RaisePropertyChanged("PdfSignatureSignerIcon");
            }
        }
        
        /// <remarks/>
        public string PdfSigPositionInFormField {
            get {
                return this.pdfSigPositionInFormFieldField;
            }
            set {
                this.pdfSigPositionInFormFieldField = value;
                this.RaisePropertyChanged("PdfSigPositionInFormField");
            }
        }
        
        /// <remarks/>
        public int PdfSigPosition {
            get {
                return this.pdfSigPositionField;
            }
            set {
                this.pdfSigPositionField = value;
                this.RaisePropertyChanged("PdfSigPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigPositionSpecified {
            get {
                return this.pdfSigPositionFieldSpecified;
            }
            set {
                this.pdfSigPositionFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigPositionSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfTransparentBackground {
            get {
                return this.pdfTransparentBackgroundField;
            }
            set {
                this.pdfTransparentBackgroundField = value;
                this.RaisePropertyChanged("PdfTransparentBackground");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfTransparentBackgroundSpecified {
            get {
                return this.pdfTransparentBackgroundFieldSpecified;
            }
            set {
                this.pdfTransparentBackgroundFieldSpecified = value;
                this.RaisePropertyChanged("PdfTransparentBackgroundSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfScaleSigImage {
            get {
                return this.pdfScaleSigImageField;
            }
            set {
                this.pdfScaleSigImageField = value;
                this.RaisePropertyChanged("PdfScaleSigImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfScaleSigImageSpecified {
            get {
                return this.pdfScaleSigImageFieldSpecified;
            }
            set {
                this.pdfScaleSigImageFieldSpecified = value;
                this.RaisePropertyChanged("PdfScaleSigImageSpecified");
            }
        }
        
        /// <remarks/>
        public string PdfSigTextSizeAndPosition {
            get {
                return this.pdfSigTextSizeAndPositionField;
            }
            set {
                this.pdfSigTextSizeAndPositionField = value;
                this.RaisePropertyChanged("PdfSigTextSizeAndPosition");
            }
        }
        
        /// <remarks/>
        public bool InvertPageRotation {
            get {
                return this.invertPageRotationField;
            }
            set {
                this.invertPageRotationField = value;
                this.RaisePropertyChanged("InvertPageRotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvertPageRotationSpecified {
            get {
                return this.invertPageRotationFieldSpecified;
            }
            set {
                this.invertPageRotationFieldSpecified = value;
                this.RaisePropertyChanged("InvertPageRotationSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfShowSignedImage {
            get {
                return this.pdfShowSignedImageField;
            }
            set {
                this.pdfShowSignedImageField = value;
                this.RaisePropertyChanged("PdfShowSignedImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfShowSignedImageSpecified {
            get {
                return this.pdfShowSignedImageFieldSpecified;
            }
            set {
                this.pdfShowSignedImageFieldSpecified = value;
                this.RaisePropertyChanged("PdfShowSignedImageSpecified");
            }
        }
        
        /// <remarks/>
        public bool PdfSigBackgroundImageTextOverlay {
            get {
                return this.pdfSigBackgroundImageTextOverlayField;
            }
            set {
                this.pdfSigBackgroundImageTextOverlayField = value;
                this.RaisePropertyChanged("PdfSigBackgroundImageTextOverlay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PdfSigBackgroundImageTextOverlaySpecified {
            get {
                return this.pdfSigBackgroundImageTextOverlayFieldSpecified;
            }
            set {
                this.pdfSigBackgroundImageTextOverlayFieldSpecified = value;
                this.RaisePropertyChanged("PdfSigBackgroundImageTextOverlaySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sign", WrapperNamespace="http://seccommerce.de/ws/SecPKI/", IsWrapped=true)]
    public partial class signRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://seccommerce.de/ws/SecPKI/", Order=0)]
        public SecSignerSoapExample.SecSignerNs.SignReq signReq;
        
        public signRequest() {
        }
        
        public signRequest(SecSignerSoapExample.SecSignerNs.SignReq signReq) {
            this.signReq = signReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignResult", WrapperNamespace="http://seccommerce.de/ws/SecPKI/", IsWrapped=true)]
    public partial class signResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://seccommerce.de/ws/SecPKI/", Order=0)]
        public SecSignerSoapExample.SecSignerNs.SignRes SignRes;
        
        public signResponse() {
        }
        
        public signResponse(SecSignerSoapExample.SecSignerNs.SignRes SignRes) {
            this.SignRes = SignRes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verify", WrapperNamespace="http://seccommerce.de/ws/SecPKI/", IsWrapped=true)]
    public partial class verifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://seccommerce.de/ws/SecPKI/", Order=0)]
        public SecSignerSoapExample.SecSignerNs.VerifyReq verifyReq;
        
        public verifyRequest() {
        }
        
        public verifyRequest(SecSignerSoapExample.SecSignerNs.VerifyReq verifyReq) {
            this.verifyReq = verifyReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyResult", WrapperNamespace="http://seccommerce.de/ws/SecPKI/", IsWrapped=true)]
    public partial class verifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://seccommerce.de/ws/SecPKI/", Order=0)]
        public SecSignerSoapExample.SecSignerNs.VerifyRes VerifyRes;
        
        public verifyResponse() {
        }
        
        public verifyResponse(SecSignerSoapExample.SecSignerNs.VerifyRes VerifyRes) {
            this.VerifyRes = VerifyRes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecSignerSoapPortTypeChannel : SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecSignerSoapPortTypeClient : System.ServiceModel.ClientBase<SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType>, SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType {
        
        public SecSignerSoapPortTypeClient() {
        }
        
        public SecSignerSoapPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecSignerSoapPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecSignerSoapPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecSignerSoapPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SecSignerSoapExample.SecSignerNs.signResponse SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType.sign(SecSignerSoapExample.SecSignerNs.signRequest request) {
            return base.Channel.sign(request);
        }
        
        public SecSignerSoapExample.SecSignerNs.SignRes sign(SecSignerSoapExample.SecSignerNs.SignReq signReq) {
            SecSignerSoapExample.SecSignerNs.signRequest inValue = new SecSignerSoapExample.SecSignerNs.signRequest();
            inValue.signReq = signReq;
            SecSignerSoapExample.SecSignerNs.signResponse retVal = ((SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType)(this)).sign(inValue);
            return retVal.SignRes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.signResponse> SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType.signAsync(SecSignerSoapExample.SecSignerNs.signRequest request) {
            return base.Channel.signAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.signResponse> signAsync(SecSignerSoapExample.SecSignerNs.SignReq signReq) {
            SecSignerSoapExample.SecSignerNs.signRequest inValue = new SecSignerSoapExample.SecSignerNs.signRequest();
            inValue.signReq = signReq;
            return ((SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType)(this)).signAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SecSignerSoapExample.SecSignerNs.verifyResponse SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType.verify(SecSignerSoapExample.SecSignerNs.verifyRequest request) {
            return base.Channel.verify(request);
        }
        
        public SecSignerSoapExample.SecSignerNs.VerifyRes verify(SecSignerSoapExample.SecSignerNs.VerifyReq verifyReq) {
            SecSignerSoapExample.SecSignerNs.verifyRequest inValue = new SecSignerSoapExample.SecSignerNs.verifyRequest();
            inValue.verifyReq = verifyReq;
            SecSignerSoapExample.SecSignerNs.verifyResponse retVal = ((SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType)(this)).verify(inValue);
            return retVal.VerifyRes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.verifyResponse> SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType.verifyAsync(SecSignerSoapExample.SecSignerNs.verifyRequest request) {
            return base.Channel.verifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SecSignerSoapExample.SecSignerNs.verifyResponse> verifyAsync(SecSignerSoapExample.SecSignerNs.VerifyReq verifyReq) {
            SecSignerSoapExample.SecSignerNs.verifyRequest inValue = new SecSignerSoapExample.SecSignerNs.verifyRequest();
            inValue.verifyReq = verifyReq;
            return ((SecSignerSoapExample.SecSignerNs.SecSignerSoapPortType)(this)).verifyAsync(inValue);
        }
    }
}
